### ISSUE TITLE
Add a Continous Integration server

### ISSUE THREAD

**Issue by wjam** [kittylyst/VillagePaymentAgent#10]
Add support for continuously building the application (travis?) and note the URL in the correct section of the Maven POM.

**Comment by wjam** [comment]
An easy solution would be to go with Travis. [Here is the documentation about setting up a Java application](http://docs.travis-ci.com/user/languages/java/).

**Comment by jm2dev** [comment]
Pull request for this issue.
https://github.com/kittylyst/VillagePaymentAgent/pull/60
