### ISSUE TITLE
Clean up JSP Mappings for HTM Files

### ISSUE THREAD

**Issue by njacobs5074** [kittylyst/VillagePaymentAgent#15]
Currently, the JSPs refer to .htm files which actually do not exist.  This is handled by a URL mapping controller in `dispatcher-servlet.xml`.

Not clear if there is any real advantage to this indirection - propose that we change the JSPs to reference the actual JSPs such as `index.jsp` instead of `index.htm`.

**Comment by gratiartis** [comment]
The indirection is generally considered to be good practice. The idea is that the actual JSP files are hidden under WEB-INF, where they are not accessible to prying eyes or browsable in any way. The .htm can map to a controller, which makes use of a JSP as a view template. Using .htm also has the benefit of not saying anything about the technology being used for the rendering. That can be handy if at a later date, a decision were to be made to switch to use Thymeleaf or GSP, for example.

Admittedly, my preference is to avoid file suffixes in URLs completely and use the HTTP accept headers to drive what kind of content I return, but that might just be me writing too many REST APIS. :)

**Comment by njacobs5074** [comment]
Makes sense to me.  I'll close this.
