### ISSUE TITLE
Eliminate Deprecated Use of Date Class

### ISSUE THREAD

**Issue by njacobs5074** [kittylyst/VillagePaymentAgent#32]
**/Users/nick/workspace/VillagePaymentAgent/src/main/java/org/haftrust/verifier/validator/IdentityDocumentValidator.java**
Warning:(129, 38) java: getYear() in java.util.Date has been deprecated
Warning:(129, 23) java: setYear(int) in java.util.Date has been deprecated
**/Users/nick/workspace/VillagePaymentAgent/src/main/java/org/haftrust/verifier/validator/VerifierValidator.java**
Warning:(103, 28) java: getYear() in java.util.Date has been deprecated
Warning:(103, 18) java: setYear(int) in java.util.Date has been deprecated

**Comment by znurgl** [comment]
I'll do this.

**Comment by znurgl** [comment]
https://github.com/kittylyst/VillagePaymentAgent/pull/36
