### ISSUE TITLE
The test database configuration does not work for multiple tests

### ISSUE THREAD

**Issue by gratiartis** [kittylyst/VillagePaymentAgent#53]
The test database connectivity uses `INIT=runscript` in the `jdbc.url` property, but does not drop the database between tests.

This is fine for tests which load configuration to be run individually. However, after a test has run, the database does not seem to be dropped. This means that if there are more than one tests which load the database config, the tests fail because the connection to the database is trying to re-run the schema creation and insert scripts.

**Comment by gratiartis** [comment]
The Spring test support does support configuring this correctly so that an in-memory database is created for each test class which loads it, but is re-used through the individual test methods within that class, without re-running initialization.

I'll have a look at what the differences are between how I usually configure this stuff and how it has been done here, to work out a decent way of improving things.

**Comment by gratiartis** [comment]
Hmm ... I think that this might just be me. I suspect that the way I'm experimenting with `@Controller` annotations is causing 2 application contexts to be initialized. I'll close this shortly if that turns out to be the case.

**Comment by kittylyst** [comment]
Can someone try to repro this, and close if not?

**Comment by njacobs5074** [comment]
They work absolutely fine from the command line.  Failing in IntelliJ, but let's consider that a separate issue.

**Comment by gratiartis** [comment]
I now have multiple DAO tests working separately without issue. It looks like the issue was related to a local (i.e. my fault) issue, where root and web contexts were both generating database schema.
