### ISSUE TITLE
Upgrade to Servlet 3.1

### ISSUE THREAD

**Issue by gratiartis** [kittylyst/VillagePaymentAgent#54]
Are there any issues relating to what this might be hosted on, which might prevent upgrading to the Servlet 3.1 API? It would be a first step towards throwing away web.xml.

**Comment by njacobs5074** [comment]
No issues that I can see - I'd eventually like to see it up & running in Spring Boot, so we'd most likely run with Tomcat 7 or Jetty 9.

Are there any other issues that are blocking this?

Thanks,

Nick

**Comment by gratiartis** [comment]
None that I can see. Just upping the version in `pom.xml` doesn't seem to cause any problems. I have updated it locally so I can wire things up in `@Configuration` classes and get rid of `AbstractWizardFormController`. I think that's the main blocker to progress in getting Spring to 4.1. Once things are on 4.1, it may well be possible to switch a `@Configuration` to `@SpringBootApplication` and delete some (maybe all) of the `@Configuration` classes.

**Comment by kittylyst** [comment]
OK - was this ever closed out? I see that my local version is on Servlet 3.1.0 & everything still seems to work?

**Comment by njacobs5074** [comment]
I don't think so.  My pom.xml still has:
```
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>2.5</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by gratiartis** [comment]
The master branch is currently on 3.1.0 and I'm not seeing any issues. Discarding the web.xml seems to be a separate issue, so I'll close this.
