### ISSUE TITLE
Intro task - findOne(id) and findAll() methods in each DAO

### ISSUE THREAD

**Issue by gratiartis** [kittylyst/VillagePaymentAgent#56]
A proposal for a reasonably simple intro task.

A couple of benefits:
 - Follows the Spring Data repository interface naming convention, facilitating that migration.
 - Enables the removal of iterating through lists in `VerifierServiceImpl` for find entities by ID.

Following a test-driven approach, the general approach could be to create a test such as:

    @RunWith(SpringJUnit4ClassRunner.class)
    @ContextConfiguration(locations = "/applicationContext.xml")
    public class DaoTest {
    
        @Autowired
        private RegionDAO regionDao;
        
        @Test
        public void shouldFindRegionById() {
            Region region = regionDao.findOne(1);
            assertNotNull(region);
        }
    
    }

... and an implementation such as:

    public Region findOne(int regionId) {
        @SuppressWarnings("unchecked")
        List<Region> regions = getHibernateTemplate().find("from Region r where r.id = ?", regionId);
        if (regions.size() == 0) {
            return null;
        }
        return regions.get(0);
    }

**Comment by njacobs5074** [comment]
Seems like a good approach to me.

As a matter of style, I'd use the ?: operator for the return statement, but
I'm not pedantic about it.  :)

On Sat, Feb 28, 2015 at 10:44 AM, Stephen Masters <notifications@github.com>
wrote:

> A proposal for a reasonably simple intro task.
>
> A couple of benefits:
>
>    - Follows the Spring Data repository interface naming convention,
>    facilitating that migration.
>    - Enables the removal of iterating through lists in VerifierServiceImpl
>    for find entities by ID.
>
> Following a test-driven approach, the general approach could be to create
> a test such as:
>
> @RunWith(SpringJUnit4ClassRunner.class)
> @ContextConfiguration(locations = "/applicationContext.xml")
> public class DaoTest {
>
>     @Autowired
>     private RegionDAO regionDao;
>
>     @Test
>     public void shouldFindRegionById() {
>         Region region = regionDao.findOne(1);
>         assertNotNull(region);
>     }
>
> }
>
> ... and an implementation such as:
>
> public Region findOne(int regionId) {
>     @SuppressWarnings("unchecked")
>     List<Region> regions = getHibernateTemplate().find("from Region r where r.id = ?", regionId);
>     if (regions.size() == 0) {
>         return null;
>     }
>     return regions.get(0);
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kittylyst/VillagePaymentAgent/issues/56>.
>



-- 
Phone: +44 7463 853 913
LinkedIn: http://uk.linkedin.com/in/njacobs5074
Twitter: @njacobs5074

**Comment by gratiartis** [comment]
To be honest, I'd prefer `?:` too. :)
I think I had the initial `if` as an early escape in my first iteration, when there were a couple more lines before the final return. When I removed those, I didn't think to try simplifying further.

Just thought if anyone has a bit of time, but is not confident about their knowledge of the system, then this is a non-invasive task, which moves things in the right direction. If no-one jumps in, I'll probably do it, but I'm trying to focus my attention on the controllers just now.

**Comment by wjam** [comment]
Note that when we've moved to Spring 4, the DAOs will all get replaced by a simple interface (issue #25)

**Comment by gratiartis** [comment]
That's the point :)

**Comment by andrewdvn** [comment]
Hi,
Emailed Ben about helping out, basic java skills, new to London Java Community. I can try and make headway on this issue if acceptable. regards Andrew.

**Comment by gratiartis** [comment]
All migrated to `JpaRepository`.

**Comment by andrewdvn** [comment]
Apologies for not contributing to this. Unfortunately or fortunately from a financial point of view I've accepted contract work relating to Oracle and some C# which precludes me from spending the kind of time I'd planned to get up to speed and contribute to the project. I'll endeavour to follow the project and time permitting get up to speed technically with the skills required. Apologies once again.

Date: Tue, 24 Mar 2015 06:47:24 -0700
