### ISSUE TITLE
Proposal - Replace StaticData with enums.

### ISSUE THREAD

**Issue by gratiartis** [kittylyst/VillagePaymentAgent#70]
Currently, various models have String fields for things like employee type and verification status. Getting rid of the static data table which drives these would make the code much more readable and less error-prone. For instance, only an `EmploymentStatus` could be passed as an argument to a method which sets the employment status. Similarly, some of the not-so-well-named properties of models would be somewhat more identifiable. None of the values I can see in that table are value which need to be changed regularly, and as they are not using unique keys, any change would wreck any existing data which references them.

**Comment by njacobs5074** [comment]
Let me review this a bit further.  I agree with your assessment that they can probably be put into an enum, but I'd like to make sure that removing them from the database is in line with the application requirements.

**Comment by gratiartis** [comment]
Enums implemented with converters created so that they map to the same values in the database. If the exact text in the database doesn't matter, then the converters could potentially be deleted and replaced with `@Enumerated` annotations.
